### ISSUE TITLE
SSH Import key call failing

### ISSUE THREAD

**Issue by mlapaglia** [nicupavel/rainmachine-api#6]
I followed the directions on https://support.rainmachine.com/hc/en-us/articles/228652648-How-to-SSH-on-Touch-HD-2nd-generation-devices used puttygen on windows to generate a key. When I put the public key into the box and hit the link I get `{ "statusCode":  3,  "message": "Invalid request !"          }`

When I do this in postman I get `{ "statusCode":  1,  "message": "Exception occurred !"       }`

![image](https://user-images.githubusercontent.com/4184746/39494467-835c37e8-4d64-11e8-8229-e51a1d05dd6b.png)

**Comment by sprinkler** [comment]
This is available only for HD12/16 models it won't work on Mini-8.
There should be more information about this error if you use VIEW LOGS from web ui.
